### ISSUE TITLE
Create browser router

### ISSUE THREAD

**Issue by raygdev** [raygdev/simply-lit#18]
I don't know how familiar you are with react router... It should feel fairly familiar because of express. It's used for client side routing. They have a newer API that the implemented within the last year that is pretty neat. It does come with some drawbacks. But it is pretty useful for not having to manually refetch data to keep everything in sync with context providers and the like. There are some performance benefits, like lesser rerender triggers being run for components and pages. But it can get pretty tricky when trying to do any authentication stuff. I have a naive workaround to it, may not be the best solution, but it does work. They allow some tools to make some UI transitions for things that the user might want to know is happening... like form submission stuff. The browser router (older router) doesn't come with those features, and there will be alot more to handle in code. If you would like to go through the manual task of it all, we can do that. If you would like to try the newer api with the data router... we can do that too. I would like to add authentication to this as well. I will create an issue for it and start working on the middleware to allow for some of that. Likely going to have to create a user schema as well. So we will have to talk about all that when it comes down to it. Like what information and things we would like to have attached to the user. I can create a separate issue for that discussion when the need arises. but for now we can talk about the router for client routing!

**Comment by raygdev** [comment]
Yes, it's an SPA. Basically it is still sent as a bundle. So the whole thing will be sent. But the component will render conditionally based on the route path that matches. 

Switch is deprecated. You would use `Routes` and `Route`. `Routes` is the replacement for `Switch`.

You would create all the routes in the `App.jsx` file. Then you would import the `BrowserRouter` as `Router` in `index.jsx` and wrap `App` with `Router` as the parent component.

**Comment by CampbellSDC** [comment]
Ok. I must have been looking at an older article. I'll try to get to the new video from Bob

**Comment by raygdev** [comment]
Ok. Don't forget to pull in changes to your working branch from upstream main if you're getting started on this so there are no conflicts. Also gave you edit access on the figma design. It had me move it to a team project instead of a draft. I don't know if there is any billing for that lol! We will see.

The new course that Bob has is based on the data router. So there will be some differences.

**Comment by raygdev** [comment]
I added a branch to this issue for the router

**Comment by CampbellSDC** [comment]
Sounds good! I'm going to go through some of the React Router course on Scrimba before diving into this.
