### ISSUE TITLE
create header component

### ISSUE THREAD

**Issue by raygdev** [raygdev/simply-lit#27]
Create a header component and start mocking up the page links. I would imagine that this will be a simple navbar/header component.  We still need to decide which route, no pun intended, is best in picking a router.

**Comment by CampbellSDC** [comment]
Do you mean  how the routes will be nested, and what the parent route will be?

**Comment by raygdev** [comment]
I'm actually going to use the ComboBox for that. I think I'm going to use the Menu component for a mobile drop-down for the navigation. I'm going to try to make the ComboBox a little more flexible so we can reuse it for filter criteria. We can get together this Sunday, if you'd like, and discuss what we want.

The ComboBox comes with an autocomplete feature that you can use. I'll need to use some context for that wheb filtering the letters. I was thinking a sidebar component for the ComboBox on desktop. And potentially a modal for mobile. 

I should have sent you a link. So you should be invited to make changes in figma. Didn't know if you wanted to mock up some designs for components or not. We cam figure that out too. But yeah, you should have an invite to make changes and stuff.

**Comment by raygdev** [comment]
I created a playground branch for playing with the ComboBox since it's new to me. I'm liking how easy it is to do things with. I was never good with tailwind lol so trying to get what I want tailwind style is going to be a learning experience! But playing with it last night, I have a baseline for what to do.
