### ISSUE TITLE
Deciding what css we will do

### ISSUE THREAD

**Issue by raygdev** [raygdev/simply-lit#30]
We need to decide on css to use. Do we want to have a separation of concerns with modular css and create our own? Do we want sass or do we want to use a component library like material or chakra? Do we want to use a css library like tailwind?

**Comment by raygdev** [comment]
@CampbellSDC I've looked at a couple of styling components foe react. For our drop-down menus that we might use and such, I think [Headless Ui](https://headlessui.com)  might be any easy approach instead of styling our own. It will be new to me too, so it would be fun to learn! It requires tailwind be used. I can install those if needed. I think that this would be a good tool to use for things that may be somewhat challenging to get going. Take a look at it and tell me what you think!

**Comment by CampbellSDC** [comment]
Also, if you would like to install those, that's totally good with me. I was looking at the Tailwind docs, and I would probably have to sit down and go through a video tutorial to see how that is all set up (I just learn better that way). So if you already have a pretty good grasp on that, I say go for it, and I'll go through that on my own time and set up yet another repository to learn that lol

**Comment by raygdev** [comment]
Ok! I'll install those later! As far as tailwind goes, they are just a bunch of utility classes that are semantically similar to what you are trying to achieve. It's pretty neat, and flexible... though when not properly used (which I'm sure I use it improperly) it can make your files look pretty cluttered with class names.

**Comment by CampbellSDC** [comment]
Awesome! Yeah, I've heard it's a lot of utility classes, which I assumed was a little similar to Bootstrap, which I got into a little bit, but, like you mentioned, it felt like everything got cluttered with class names and I (with my ADHD) would get super overwhelmed with it, so I've just stuck to vanilla CSS

**Comment by raygdev** [comment]
It is a bit cumbersome lol but we can create a utility classes of our own using tailwind if that would be more useful. They have an @use feature you can use to construct a class from their utility classes... assuming we see a pattern of reuse with the same group of utility classes. Tailwind advises to avoid a pattern like that, but it is our project lol so we can do what we want 😆

**Comment by raygdev** [comment]
Some other things to note, tailwind has a mobile first approach. So anything any breakpoints we use with their utils would be for that size and larger. Also, it would be useful to let css inheritance do it's magic when writing tailwind in components. I'm sure their are other things to note... but that's all I can think of at this point.

**Comment by raygdev** [comment]
We will likely need to discuss a color scheme to decide what we want to do to make a consistent feel. We can add those as tailwind colors as well. We can also use their color pallet. It's pretty robust. Let me know your thoughts!
